function status = check_toolboxes()
%CHECK_TOOLBOXES Return installed/version/licence status without failing on optionals.
products = { ...
    "MATLAB", "MATLAB"; ...
    "Image Processing Toolbox", "Image_Toolbox"; ...
    "Computer Vision Toolbox", "Video_and_Image_Blockset"; ...
    "Deep Learning Toolbox", "Neural_Network_Toolbox"; ...
    "Medical Imaging Toolbox", "Medical_Imaging_Toolbox"; ...
    "Statistics and Machine Learning Toolbox", "Statistics_Toolbox"; ...
    "Simulink", "Simulink"; ...
    "SimEvents", "SimEvents"};
installed = ver;
status = struct();
for index = 1:size(products, 1)
    name = products{index, 1};
    key = matlab.lang.makeValidName(name);
    match = strcmp({installed.Name}, name);
    status.(key) = struct( ...
        "installed", any(match), ...
        "version", join(string({installed(match).Version}), ","), ...
        "licenceAvailable", logical(license("test", products{index, 2})));
end
disp(status)
end
