function p = parameters()
%PARAMETERS Default one-day rural clinic assumptions; all values configurable.
% aiMinutes is conservative station time; V3.4 warm inference measured 0.636 s.
p = struct( ...
    "name", "baseline_rural_clinic", "seed", 26038, "minutes", 480, ...
    "arrivalRatePerMinute", 0.10, "cameraCount", 1, "cameraMinutes", 6, ...
    "aiDeviceCount", 1, "aiMinutes", 1.2, "reviewerCount", 1, "reviewMinutes", 8, ...
    "networkMinutes", 1.5, "useBandwidthModel", true, "imageSizeMB", 5, ...
    "bandwidthMbps", 10, "networkOverheadMinutes", 1.43333333333333, ...
    "poorQualityRate", 0.12, "referableRate", 0.28, "uncertainRate", 0.10, ...
    "severeRateWithinReferable", 0.25, "priorityReview", false, ...
    "workingDaysPerYear", 250);
end
